### ISSUE TITLE
"cached location" 

### ISSUE THREAD

**Issue by Yajsam** [RonanPlugins/BetterRTP#101]
My idea for is to have a player save a location that they would teleport back to when using RTP. 
They would not go to a new location, rather the same one for a set period of time. 
Then after the cooldown could be assigned a NEW RTP location.

**Comment by SuperRonanCraft** [comment]
mhh, this is an interesting idea, would make the rtp command not completely useless until a players cooldown expires. Ima mess with this idea a bit.

**Comment by iiMilan** [comment]
@SuperRonanCraft this is implemented right?

**Comment by SuperRonanCraft** [comment]
Not yet atleast, I would like to add this soon though
