### ISSUE TITLE
hook in the minePlots plugin so it doesn't teleport players to other plots

### ISSUE THREAD

**Issue by Maker200** [RonanPlugins/BetterRTP#125]
**Plugin Version**:

**Request**:

**How/Why**:

**Comment by Maker200** [comment]
Version: 3.6.1
Request:  Can you add a hook in the minePlots plugin so it doesn't teleport players to other plots?
How/why: Because players teleport to other plots.

**Comment by ARR4NN** [comment]
Added support in #130
