### ISSUE TITLE
BetterRTP loads lots of chunks

### ISSUE THREAD

**Issue by a1375625918** [RonanPlugins/BetterRTP#127]
**Plugin Version**: 3.6.2

**Describe The Bug**:

BetterRTP won't stop loading new chunks if no safe location is found.

**How To Reproduce**:

1. Start a new Spigot 1.19.3 server with BetterRTP. Set `level-type=minecraft\:flat` in server.properties.
2. BetterRTP loads many new chunks. Since queue is enabled by default but `MinY` is 0, it can't find any safe location in this superflat world. Around 100MB disk space is occupied by the world after 10 minutes.
3. Set `MaxRadius: 50000` in config.yml of BetterRTP and restart server. Around 1GB disk space is gone in another 10 minutes.

**Expected Behavior**:

BetterRTP may automatically add worlds that don't seem to have safe places to `DisableWorlds` , or somehow prevent it from meaningless queueing. A configuration item of maximum tries before auto disable can be added too. 

**Screenshots/Error Log**:

_No errors in log._

**Additional Context**:

This server is running CraftBukkit version 3669-Spigot-454acb7-f150cfb (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT)

**Comment by savoie7304** [comment]
I had the same problem as you !
I searched for 2 days which plugin causes this problem !

**Comment by alazeprt** [comment]
I had the same problem as you!

**Comment by alazeprt** [comment]
I am developing a random teleport plugin that will solve this problem and will be released soon

**Comment by a1375625918** [comment]
I'm sorry to hear that this issue is closed as invalid without any explanation. I tried the most recent BetterRTP version 3.6.8-2 but the problem persists. Logs are available at https://pastebin.com/7wJB3JG8 . ChunkLogger is a simple piece of code that listens to ChunkLoadEvent and prints a line to console when `event.isNewChunk()==true` . Please let me know if you need more information about this.
