### ISSUE TITLE
Folia support: java.lang.UnsupportedOperationException: null

### ISSUE THREAD

**Issue by Aitooor** [RonanPlugins/BetterRTP#132]
**Plugin Version**:
Version: 3.6.8-2

**Describe The Bug**:
java.lang.UnsupportedOperationException: null

**How To Reproduce**:
1. Drop the plugin in Folia plugins folder
2. Start the server

**Expected Behavior**:

**Screenshots/Error Log**:
Error Log: https://paste.md-5.net/qujudovapo.cs

**Additional Context**:
I think is the scheduler
I see this commit: https://github.com/RonanPlugins/BetterRTP/commit/a1c266ffca5be83a789e18c67013faba237580a4

**Comment by SuperRonanCraft** [comment]
Version 3.6.8 technically added folia support. Were waiting on one of our dev team to create a library to allow easy folia support while building on Java 8

**Comment by Aitooor** [comment]
> Version 3.6.8 technically added folia support. Were waiting on one of our dev team to create a library to allow easy folia support while building on Java 8

Nice. Thanks jeje
