### ISSUE TITLE
Cross-server support

### ISSUE THREAD

**Issue by kristofferous** [RonanPlugins/BetterRTP#134]
**Request**:
 Gimme gimme

**How/Why**:
 It's requested, and cool

**Comment by SuperRonanCraft** [comment]
only way I think this would be possible is with have a cross-server request be saved a database and have betterrtp save data differently as two servers might have the same world name so we can handle cooldowns and such as normal

**Comment by kristofferous** [comment]
Dew it

**Comment by SuperRonanCraft** [comment]
**insert worried face**
