### ISSUE TITLE
Java 1.0 Support

### ISSUE THREAD

**Issue by TechnicallyCoded** [RonanPlugins/BetterRTP#138]
**Plugin Version**:
v3.6.9-1

**Request**:
My minecraft alpha server runs on Java 1.0. Please add support for Java 1.0 or I will leave a 1 star review.

**How/Why**:
How? Idfk
Why? Because you can't, I know you can't.

(For the random person reading this, no this isn't sarcasm whatsoever, I need my toaster to run minecraft but I can't /rtp)

**Additional Context**:
I have 200 IQ according to Cortana

**Comment by ARR4NN** [comment]
please no

**Comment by TechnicallyCoded** [comment]
:)
