### ISSUE TITLE
Don't transfer after using command

### ISSUE THREAD

**Issue by doubiovo** [RonanPlugins/BetterRTP#153]
**Plugin Version**:3.6.10

**Describe The Bug**:As shown in the figure, if/rtp is input, it will not be transmitted, and if rtp is used again, it will be prompted that it is being transmitted。version：1.20.1

**How To Reproduce**:
1./rtp
2./rtp again

**Expected Behavior**:Normal transmission

**Screenshots/Error Log**:

[1.zip](https://github.com/RonanPlugins/BetterRTP/files/11817021/1.zip)

**Additional Context**:

**Comment by TechnicallyCoded** [comment]
The picture you sent uses a language I don't know. Please use the english version to make the problem happen again. Then send us the error in english. Once that is all done, feel free to change it back to your language.

**Comment by doubiovo** [comment]
> 您发送的图片使用了我不懂的语言。请使用英文版本使问题再次发生。然后用英语向我们发送错误。完成所有操作后，请随时将其更改回您的语言。

![image](https://github.com/RonanPlugins/BetterRTP/assets/103913734/ece954d6-fee8-4342-871e-08e8dcb89c63)

**Comment by TechnicallyCoded** [comment]
I think this was fixed in a recent commit. You may have to wait a few days for the update to be posted. If not fixed in the next version, send another message.

**Comment by doubiovo** [comment]
> I think this was fixed in a recent commit. You may have to wait a few days for the update to be posted. If not fixed in the next version, send another message.

After multiple tests, I have determined that this 100% is caused by the Respect Residence area.You can test it, it's absolutely true

**Comment by pjindras** [comment]
The same problem here, I had to disable residence area respectation.

**Comment by YuanYuanOwO** [comment]
Same issue
Disable the Residence and WorldGuard respect can solve this issue

**Comment by wling-art** [comment]
Yes, I'm experiencing this problem as well, and it's affecting my server in particular!
