### ISSUE TITLE
[feature request] RTP Failed Event

### ISSUE THREAD

**Issue by quiquelhappy** [RonanPlugins/BetterRTP#173]
**Plugin Version**:
latest

**Request**:
Add an API event when an RTP failed

**How/Why**:
Using the craftbukkit events API

**Additional Context**:
Please, include information about the RTP, such as the RTP type

**Comment by SuperRonanCraft** [comment]
This is a great idea, would be nice to get some feedback on the event to why a rtp failed

**Comment by SuperRonanCraft** [comment]
This has been added, pending release ;)
