### ISSUE TITLE
Essentials and BetterRTP error

### ISSUE THREAD

**Issue by Rustbreaker17** [RonanPlugins/BetterRTP#176]
**Version #3.6.10**:

**Describe The Bug**:

when i use rtp, I get the following error in my console

**How To Reproduce**:

Steps to reproduce the behavior
1. First add some bunch of plugins along with BetterRTP. Make sure to add Essentialsx
2.  now in IN-GAME type /rtp

**Expected Behavior**:

You will get the following error log which was given above [ERROR](https://pastebin.com/qSfBZNvy)
**Screenshots/Error Log**:

**Comment by SuperRonanCraft** [comment]
Love it when core plugins keep changing their API. I'll see what changed and update appropriately ;)

**Comment by SuperRonanCraft** [comment]
This has been fixed by... ignoring it and adding a try/catch statement xD
will be going out in upcoming update

**Comment by SuperRonanCraft** [comment]
This has been patched in 3.6.12
