### ISSUE TITLE
Instantly teleport without delay or cooldown - problem

### ISSUE THREAD

**Issue by smscentras** [RonanPlugins/BetterRTP#179]
**Plugin Version**:
1.8.8

**Describe The Bug**:
Allowing players to instantly teleport without delay or cooldown?
After using command /rtp (with cooldown 100) - try to enter portal and your plugin write message: wait 90sec more... (this is ok)
After that, no longer portal working... Need to reconnect. (not ok)

**How To Reproduce**:
Turn RTP cooldown to 100
write /rtp
write /rtp
Try go thrrough the gate... bum

**Expected Behavior**:
Portal allowing players to instantly teleport without delay or cooldown?  - Not working.
Crash on cooldown and can't working, need to rejoin the world.

**Screenshots/Error Log**:
No errors in console.

**Comment by SuperRonanCraft** [comment]
This has been added, just pending release ;) Great recommendation

**Comment by SuperRonanCraft** [comment]
This has been fixed, pending release ;)

**Comment by SuperRonanCraft** [comment]
fixed in 3.6.12
