### ISSUE TITLE
Magic Button

### ISSUE THREAD

**Issue by grabeq123** [RonanPlugins/BetterRTP#180]
Please add to the plugin the ability to create a "Magic Button" on spawn which, after placing and clicking on it by the player, will move him to random cords

**Comment by TechnicallyCoded** [comment]
This sounds like customized server behavior specific to your needs. The BetterRTP plugin is general RTP plugin and doesn't add hyper-specific behavior like this.

Please get in contact with a developer who can make this happen for you or try to learn how to make your own plugins. They/You can use BetterRTP as a platform to handle the random teleportation part but your custom button feature is for you/or the dev to figure out.
