### ISSUE TITLE
Please add the ability to randomly teleport after character death.  

### ISSUE THREAD

**Issue by TheFaik** [RonanPlugins/BetterRTP#185]
**Plugin Version**:
3.6.11

**Request**:
Please add the ability to randomly teleport after character death.

**Comment by SuperRonanCraft** [comment]
This has been added, pending release, great recommendation

**Comment by smscentras** [comment]
> This has been added, pending release, great recommendation

At the first - try to remove bug in cooldown. Read all issues!

**Comment by SuperRonanCraft** [comment]
New option RTPOnDeath option added to Default and Custom world options. Added in 3.6.12
