### ISSUE TITLE
Add a ukrainian language

### ISSUE THREAD

**Issue by Zeith22** [RonanPlugins/BetterRTP#191]
**Plugin Version**: 3.6.12

**Request**: Add a ukrainian language

**How/Why**: Because ukrainian language cool

**Additional Context**: 
[Translation](https://github.com/RonanPlugins/BetterRTP/files/13855428/BetterRTP_translation_rework.txt)

**Comment by Zeith22** [comment]
Translated by Mesh_29

**Comment by Yomamaeatstoes** [comment]
Can you please create a PR with this language addition for it to be reviewed?
