### ISSUE TITLE
Folia RTP error

### ISSUE THREAD

**Issue by DarkyG2** [RonanPlugins/BetterRTP#198]
**Plugin Version**:

3.6.12
**Describe The Bug**:

When doing RTP I'm getting this error: https://pastebin.com/UBiAcpp6
**How To Reproduce**:

1. do /rtp
2. boom error
**Expected Behavior**:

no errors
**Screenshots/Error Log**:

https://pastebin.com/UBiAcpp6
**Additional Context**:

Folia 1.20.4

**Comment by ddsb520** [comment]
![image](https://github.com/RonanPlugins/BetterRTP/assets/96320440/8d04f9ee-a08a-40e1-9d09-3b2eecf814f4)

**Comment by Yomamaeatstoes** [comment]
Fixed in the latest version

**Comment by TechnicallyCoded** [comment]
Resolved
