### ISSUE TITLE
Random teleportation cancellation function

### ISSUE THREAD

**Issue by TheFaik** [RonanPlugins/BetterRTP#203]
**Version**: BetterRTP 3.6.12

**Request**: Add exceptions to random teleportation if the player has a respawn on the bed and a respawn anchor, and also if the player has set /sethome (essentialsX & CMI). (translated using Google Translate) 

**How/Why**: Because if a player places a spawn point on a bed, while the random teleportation function is enabled, he will still be teleported to a random point, and not to the bed. Also with the home point set (/sethome) from the EssentialsX & CMI plugins.

**Additional Context**: :(

**Comment by noslowd0wn** [comment]
Just enable RTPOnDeath in config.uml

**Comment by TheFaik** [comment]
Надеюсь меня услышат...

**Comment by noslowd0wn** [comment]
> Надеюсь, меня услышат...

Я честно говоря не совсем то и понял, что тебе нужно то?

**Comment by TheFaik** [comment]
I have already solved this problem by writing a script.
In short, I would like to add an exception. For example: A player has a sethome from EssentialX and wanted it to teleport the player to their home (/home) instead of randomly teleporting. Similarly with beds, if the player had a spawn point near the bed, then he was teleported there instead of randomly teleporting after death. I'll send you the script and it will be clear to you right away. Download BetterRTP, EssentialsX, Skript(https://github.com/SkriptLang/Skript/releases), Script-reflect(https://github.com/SkriptLang/skript-reflect/releases/tag/v2.4) And install script to the script folder.
[Uploading rtp.zip…]()


> > Надеюсь, меня услышат...
> 
> Я честно говоря не совсем то и понял, что тебе нужно то?

**Comment by TheFaik** [comment]
First try to kill yourself and you should be teleported randomly. Then try to put /sethome and die again and you will be teleported to your set home (/home). Same with beds. Place the bed and right-click on the bed and your spawn point will be set according to the vanilla standard and try to die again and you will be teleported next to the bed. (if there is a rhinestone /sethome and the spawn point is near the bed, then priority is given to the spawn point to the bed, then teleport will be to the bed, not to /home)

**Comment by noslowd0wn** [comment]
> First try to kill yourself and you should be teleported randomly. Then try to put /sethome and die again and you will be teleported to your set home (/home). Same with beds. Place the bed and right-click on the bed and your spawn point will be set according to the vanilla standard and try to die again and you will be teleported next to the bed. (if there is a rhinestone /sethome and the spawn point is near the bed, then priority is given to the spawn point to the bed, then teleport will be to the bed, not to /home)

Did you need just to randomly teleport the player on death only if he didn't have any homes or other priority "teleport places"?

**Comment by TheFaik** [comment]
> > Сначала попытайтесь убить себя, и вас телепортируют случайным образом.  Затем попробуйте поставить /sethome и умереть еще раз, и вы будете телепортированы в свой заданный дом (/home).  То же самое с кроватями.  Поместите кровать и щелкните правой кнопкой мыши на кровати, и ваша точка появления будет установлена ​​в соответствии со стандартом ванили. Попробуйте умереть еще раз, и вы будете телепортированы рядом с кроватью.  (если есть страз /sethome и точка спавна возле кровати, то приоритет отдается точке спавна на кровать, тогда телепорт будет к кровати, а не в /home)
> 
> Вам нужно было просто случайным образом телепортировать игрока после смерти, только если у него не было домов или других приоритетных «мест телепортации»?

yes.
